spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/moment
    username: root
    password: Qwerty;*#06#
    driver-class-name: com.mysql.jdbc.Driver
  http:
    multipart:
      location: C:/img/
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${spring.http.multipart.location}